# Generated by Django 4.0 on 2021-12-28 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('find_a_volunteer_dir', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer_profile',
            name='owner_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.customuser'),
        ),
        migrations.AddField(
            model_name='organisation_profile',
            name='owner_id',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to='users.customuser'),
        ),
        migrations.AddField(
            model_name='matched_volunteers',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='find_a_volunteer_dir.organisation_profile'),
        ),
        migrations.AddField(
            model_name='matched_organisations',
            name='volunteer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='find_a_volunteer_dir.volunteer_profile'),
        ),
        migrations.AddField(
            model_name='accepted_volunteers',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='find_a_volunteer_dir.organisation_profile'),
        ),
        migrations.AddField(
            model_name='accepted_organisations',
            name='volunteer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='find_a_volunteer_dir.volunteer_profile'),
        ),
    ]
