# Generated by Django 4.0 on 2022-01-18 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_volunteer_dir', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matched_organisations',
            name='matched',
        ),
        migrations.RemoveField(
            model_name='matched_organisations',
            name='volunteer',
        ),
        migrations.AddField(
            model_name='matched_organisations',
            name='id_of_matched_organisation',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matched_organisations',
            name='volunteer_owner_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
