# Generated by Django 4.0 on 2022-01-18 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_volunteer_dir', '0003_remove_matched_organisations_matched_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matched_organisations',
            name='organisation_compatibility_score',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
