# Generated by Django 4.0 on 2022-01-19 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('find_a_volunteer_dir', '0004_matched_organisations_organisation_compatibility_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accepted_organisations',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='accepted_organisations',
            name='volunteer',
        ),
        migrations.AddField(
            model_name='accepted_organisations',
            name='decision',
            field=models.CharField(choices=[('Accept', 'Accept'), ('Reject', 'Reject')], default='reject', max_length=15),
        ),
        migrations.AddField(
            model_name='accepted_organisations',
            name='id_of_accepted_organisation',
            field=models.IntegerField(default=9),
        ),
        migrations.AddField(
            model_name='accepted_organisations',
            name='volunteer_owner_id',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to='users.customuser'),
        ),
    ]
