# Generated by Django 4.0 on 2022-01-19 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_volunteer_dir', '0005_remove_accepted_organisations_accepted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accepted_organisations',
            name='volunteer_owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='find_a_volunteer_dir.volunteer_profile', to_field='owner_id'),
        ),
    ]
