# Generated by Django 4.0 on 2022-01-27 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_volunteer_dir', '0006_alter_accepted_organisations_volunteer_owner_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accepted_organisations',
            options={},
        ),
        migrations.AlterModelOptions(
            name='matched_organisations',
            options={},
        ),
    ]
