# Generated by Django 4.0 on 2022-02-01 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_volunteer_dir', '0007_alter_accepted_organisations_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='verification_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.IntegerField()),
                ('captcha_answer', models.CharField(blank=True, max_length=20)),
                ('interpreted_written_digit', models.CharField(blank=True, max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='matched_volunteers',
            name='organisation',
        ),
        migrations.DeleteModel(
            name='accepted_volunteers',
        ),
        migrations.DeleteModel(
            name='matched_volunteers',
        ),
    ]
