# Generated by Django 4.0 on 2022-03-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_volunteer_dir', '0008_verification_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification_details',
            name='verified',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
