# Generated by Django 4.0 on 2022-03-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_volunteer_dir', '0009_verification_details_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='image_upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='C:/Users/arunh/Python NEA/find_a_volunteer/user_uploaded_images/')),
            ],
        ),
    ]
