# Generated by Django 4.0 on 2022-03-18 23:32

from django.db import migrations, models
import find_a_volunteer_dir.models


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_volunteer_dir', '0010_image_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_upload',
            name='user_id_of_uploader',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image_upload',
            name='image',
            field=models.ImageField(upload_to=find_a_volunteer_dir.models.rename_and_path),
        ),
    ]
