# Generated by Django 4.0 on 2022-03-19 13:23

from django.db import migrations, models
import find_a_volunteer_dir.models


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_volunteer_dir', '0011_image_upload_user_id_of_uploader_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_upload',
            name='image',
            field=models.ImageField(storage=find_a_volunteer_dir.models.OverwriteStorage(), upload_to=find_a_volunteer_dir.models.rename_and_path),
        ),
    ]
